#! /bin/sh

export BSPWM_CONFIG="$HOME/.config/bspwm"
export BSPWM_SCRIPTS="$HOME/.config/bspwm/scripts"

export SXHKD_CONFIG="$HOME/.config/sxhkd/sxhkdrc"
export POLYBAR_CONFIG="$HOME/.config/polybar/config.ini"
export PICOM_CONFIG="$HOME/.config/picom/picom.conf"
export DUNST_CONFIG="$HOME/.config/dunst"

export WALCACHE="$HOME/.cache/wal"
export DISCORD_THEMES="$HOME/.cache/wal/"

export _JAVA_AWT_WM_NONREPARENTING=1
export XDG_CURRENT_DESKTOP='bspwm'

PATH="$BSPWM_SCRIPTS:$PATH"

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         1
bspc config window_gap          25

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_frame_opacity 0.75
bspc config focused_frame_opacity 0.75

bspc config focus_follows_pointer true
bspc config history_aware_focus true
bspc config focus_by_distance true
bspc config pointer_motion_interval 5

xsetroot -cursor_name left_ptr &

xrdb -merge $HOME/.cache/wal/colors.Xresources &
wal -r
feh --bg-fill "$HOME/Downloads/milad-fakurian-xUtskxO_-CQ-unsplash.jpg" &

source ~/.cache/wal/colors.sh
bspc config normal_border_color $color1
bspc config active_border_color $color2
bspc config focused_border_color $foreground
bspc config focus_follows_pointer true

function run {
	if ! pgrep $1
	then
	    $@&
	fi
}

# AUTO START
run alacritty -e flatpak run com.spotify.Client & disown
run alacritty -e flatpak run com.discordapp.Discord & disown
run alacritty -e flatpak run org.mozilla.firefox & disown
run alacritty -e spicetify restore backup apply & disown
